### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by krash84** [PeculiarVentures/CAdES.js#2]
Добрый день!

Пытаюсь собрать пример с помощью следующих команд:

```npm run build
//... а потом
npm run build:examples
```

вторая падает:

```$ npm run build:examples

> cadesjs@1.0.11 build:examples /home/jetbird/workspace/alt/CAdES.js
> npm run ex1


> cadesjs@1.0.11 ex1 /home/jetbird/workspace/alt/CAdES.js
> cd examples/CAdESComplexExample && npm run build && cd ../..


> @ build /home/jetbird/workspace/alt/CAdES.js/examples/CAdESComplexExample
> rollup -c && sed -f ../script.sed  es6.js > ../../test/cadesComplexExample.js


es6.js → bundle.js, ../../test/browser/cadesComplexExample.js...
[!] TypeError: Cannot use 'in' operator to search for 'signedAttrs' in undefined
TypeError: Cannot use 'in' operator to search for 'signedAttrs' in undefined
    at in (/home/jetbird/workspace/alt/CAdES.js/node_modules/rollup/dist/rollup.js:10099:49)
    at BinaryExpression.getLiteralValueAtPath (/home/jetbird/workspace/alt/CAdES.js/node_modules/rollup/dist/rollup.js:10119:16)
    at IfStatement.getTestValue (/home/jetbird/workspace/alt/CAdES.js/node_modules/rollup/dist/rollup.js:10742:31)
    at IfStatement.hasEffects (/home/jetbird/workspace/alt/CAdES.js/node_modules/rollup/dist/rollup.js:10677:73)
    at BlockStatement$$1.hasEffects (/home/jetbird/workspace/alt/CAdES.js/node_modules/rollup/dist/rollup.js:9946:22)
    at ForOfStatement$$1.hasEffects (/home/jetbird/workspace/alt/CAdES.js/node_modules/rollup/dist/rollup.js:10618:23)
    at ForOfStatement$$1.NodeBase.shouldBeIncluded (/home/jetbird/workspace/alt/CAdES.js/node_modules/rollup/dist/rollup.js:9236:38)
    at BlockStatement$$1.include (/home/jetbird/workspace/alt/CAdES.js/node_modules/rollup/dist/rollup.js:9954:22)
    at FunctionDeclaration$$1.NodeBase.include (/home/jetbird/workspace/alt/CAdES.js/node_modules/rollup/dist/rollup.js:9165:23)
    at FunctionDeclaration$$1.FunctionNode.include (/home/jetbird/workspace/alt/CAdES.js/node_modules/rollup/dist/rollup.js:9498:34)


npm ERR! Linux 4.14.30-un-def-alt0.M80P.1
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build: `rollup -c && sed -f ../script.sed  es6.js > ../../test/cadesComplexExample.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'rollup -c && sed -f ../script.sed  es6.js > ../../test/cadesComplexExample.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rollup -c && sed -f ../script.sed  es6.js > ../../test/cadesComplexExample.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jetbird/workspace/alt/CAdES.js/examples/CAdESComplexExample/npm-debug.log

npm ERR! Linux 4.14.30-un-def-alt0.M80P.1
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "ex1"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! cadesjs@1.0.11 ex1: `cd examples/CAdESComplexExample && npm run build && cd ../..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cadesjs@1.0.11 ex1 script 'cd examples/CAdESComplexExample && npm run build && cd ../..'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cadesjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd examples/CAdESComplexExample && npm run build && cd ../..
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cadesjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cadesjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jetbird/workspace/alt/CAdES.js/npm-debug.log

npm ERR! Linux 4.14.30-un-def-alt0.M80P.1
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:examples"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! cadesjs@1.0.11 build:examples: `npm run ex1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cadesjs@1.0.11 build:examples script 'npm run ex1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cadesjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run ex1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cadesjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cadesjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jetbird/workspace/alt/CAdES.js/npm-debug.log
```

до этого делал npm install в каталоге CAdES.js.

P.S.
вопрос не совсем по теме, но все же (просто не знаю, у кого еще спросить): существует ли какая-нибудь открытая библиотека или инструментарий для создания/проверки подписи в формате CAdES, в частности, CAdES Long Type 1, на C++? Или Python? Насколько это трудоемко? Есть ли какой-нибудь tutorial, где для чайников расписано, как это делается? :)

**Comment by rmhrisk** [comment]
Leonid, I am not aware of a turn-key CAdES library in C++ or python. All implementations I have seen are more-or-less application-specific layers on OpenSSL or similar.

@YuryStrozhevsky will help with the example not working.

**Comment by YuryStrozhevsky** [comment]
@spike-spb It is not a directly issue of CAdES.js - the problem mainly related to latest `rollup` release. I have checked - the issue resolves automatically when installing previouse version of `rollup`:
```command
npm i rollup@0.60.0
```
I will check with `rollup` support what is going on.

As for CAdES libraries: as fas as I know there are no open source libraries on C++ having CAdES support. But if you would like only create such signatures on C++ you could try BouncyCastle or library from CryptoPRO. As for texts about CAdES - [here is mine](https://habr.com/post/214295/). Have not seen any other good articles about CAdES, but probably there are :)

**Comment by YuryStrozhevsky** [comment]
@spike-spb The issue fixed via fix for [this issue](https://github.com/rollup/rollup/issues/2337). So, now in order to successfully build CAdES.js example you need to install latest version of `rollup`:
```command
npm i rollup@0.63.2
```

**Comment by krash84** [comment]
Спасибо! Все заработало.
У меня еще 1 вопрос по второй части примера: загрузка данных CAdES. Я так понял, туда не подойдет подпись, которая создается в 1-й части? Я пробовал записать ее в файл, и загрузить, но ничего не получилось.
